services:
  - type: web
    name: quitpuff
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py