services:
  - type: web
    name: quitpuff
    env: docker
    region: singapore
    dockerfilePath: ./Dockerfile
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production